### PR TITLE
Waveform audio / Playback without `ffplay`

### LINKED ISSUE #1: Suggestion: Use Waveform format and enable use without ffmpeg
Just a small suggestion to enable usage _without_ ffmpeg, provided one of the following commands is available on the system: `aplay`, `paplay`, `pw-play`. If the mp3 files are changed to a waveform format (`success.wav`), they can be played directly with any of these.

This would allow easier integration on systems where ffmpeg may need to be installed from a 3rd party or built from source. This creates an out-of-the box experience for some users.

### PR DESCRIPTION
**Pull request by TheFlagCourier**
This PR enables direct playback over PipeWire, PulseAudio, or Alsa; so long as the appropriate utility packages are installed on the host system.

### Major Changes

- Replaced MP3 clips with WAV clips.
- Makes `ffplay` an optional dependency, instead of required.
- Adds `pw-play` (`pw-cat`), `paplay` (`pacat`), and `aplay` as optional dependencies.
- Adds `sound_util` function for selection and debugging. _No longer exposed to PATH._

### Utility Precedence

`ffplay` >> `pw-play` >> `paplay` >> `aplay` >> _none (run command with a warning)_

### Example Usage 
(ROB.cow provided by https://github.com/charc0al/cowsay-files; only used as example)

https://user-images.githubusercontent.com/2712890/164883834-85776a5d-04f2-4d30-a235-33428835ccbe.mp4

Closes #1

### CODE REVIEW

**Comment by sudofox** [comment]
I'm out of the hospital. Hurray!

A bit of feedback: Having melee_sound_util on the PATH will mean that people tab completing will complete to `melee` instead of `melee[space]` meaning they'll have to hit space, no bueno for the power user. The function should be encapsulated inside of melee() just the same as success and failure is instead of being separate -- debug ability isn't really necessary for this; I think this script should limit itself to only providing that one single function.

Regarding the file exists check in .bashrc: I reckon it would be better to have it error out when you've put the wrong path in instead of silently failing, to aid during installation. 90% of the time I'd like an error instead of silent failure when trying to set something up. If you can think of a reason besides that, though, I'd be glad to hear it

Side note: very pleased to report that this PR adds Termux compatibility, so it runs on my phone. :D

**Comment by TheFlagCourier** [comment]
> I'm out of the hospital. Hurray!

Glad to hear that!

I've gone ahead and followed your advice. 

The reason I had exposed `melee_sound_util` was that it would fail for me in a [toolbox](https://containertoolbx.org/) environment, and was using it to troubleshoot the logic. Mostly unnecessary now, so re-nesting shouldn't be an issue.

As for the `.bashrc` check in the documentation, I was simply following what `.bash_profile` typically does when it sources `.bashrc`. Your reasoning seems sound here, so I've gone ahead and reverted that part.

Also, had no idea Termux would work!  :shipit:

**Comment by sudofox** [comment]
One more thing and note I haven't tested your latest commit because I'm very bleary

**Comment by sudofox** [comment]
One more thing and no I haven't tested since your previous commit, but did you replace the sound files I was using with something entirely different? I created those ones myself with audacity to add similar reverb effects to those in the game. I don't hear that reverb on termux. They should be 2.5 seconds long iirc

I'll check in an hour or few, I just woke but I'm still very tired

**Comment by TheFlagCourier** [comment]
Yes. I personally hear no real discernible difference. But after checking, I do see that some processing was done to the repo's mp3. (Middle is direct conversion with ffmpeg, top is raw from the game.)

image

**Comment by sudofox** [comment]
will review soon ty!

**Comment by sudofox** [comment]
lgtm

**Pull request merged**
